import React, { useMemo } from "react";
import "../App.css";
 
function ExportSummary({ setPage, tripBills = [], tripMembers = [], userProfile }) {
  const total = tripBills.reduce((sum, b) => sum + (Number(b.amount) || 0), 0);
  const settled = tripBills.filter(b => b.status === "Finished").length;
 
  const balances = useMemo(() => {
    const bal = {};
    tripMembers.forEach(m => { bal[m] = 0; });
    tripBills.forEach((bill) => {
      const amt = Number(bill.amount) || 0;
      const participants = bill.sharedBy?.length > 0 ? bill.sharedBy : tripMembers;
      const share = amt / participants.length;
      if (bal[bill.paidBy] !== undefined) bal[bill.paidBy] += amt;
      participants.forEach(p => { if (bal[p] !== undefined) bal[p] -= share; });
    });
    return bal;
  }, [tripBills, tripMembers]);
 
  const getCategoryIcon = (cat) =>
    ({ Food:"🍜", Ticket:"🎫", Transport:"🚕", Merch:"🛍️", Hotel:"🏨" }[cat] || "💸");
 
  const catMap = {};
  tripBills.forEach(b => {
    catMap[b.category] = (catMap[b.category] || 0) + (Number(b.amount) || 0);
  });
 
  const handleShare = () => {
    const lines = [
      "🧾 NeoSplit - Trip Summary",
      "═══════════════════════",
      `💰 Total: ${total.toLocaleString()} THB`,
      `✅ Settled: ${settled}/${tripBills.length} bills`,
      "",
      "📊 Bills:",
      ...tripBills.map(b => `  • ${b.name}: ${Number(b.amount).toLocaleString()} THB (${b.paidBy})`),
      "",
      "💳 Balances:",
      ...Object.entries(balances).map(([name, bal]) =>
        `  ${name}: ${bal >= 0 ? "+" : ""}${bal.toFixed(2)} THB`
      ),
      "",
      "Generated by NeoSplit 🚀"
    ].join("\n");
 
    if (navigator.share) {
      navigator.share({ title: "NeoSplit Summary", text: lines });
    } else {
      navigator.clipboard.writeText(lines);
      alert("คัดลอกสรุปแล้วครับ! 📋");
    }
  };
 
  return (
    <div className="ns-screen">
 
      {/* ── Header ── */}
      <div className="ns-page-header">
        <button className="ns-back-btn" onClick={() => setPage("settlement")}>‹</button>
        <span className="ns-title">Export Summary</span>
        <div style={{ width: 36 }} />
      </div>
 
      {/* ── Hero ── */}
      <div className="ns-card" style={{
        background: "linear-gradient(135deg, rgba(0,255,133,0.1), rgba(0,255,133,0.03))",
        border: "1px solid rgba(0,255,133,0.2)", marginBottom: 14, textAlign: "center",
      }}>
        <div style={{ fontSize: 36, marginBottom: 8 }}>🧾</div>
        <div style={{ fontFamily: "var(--ns-syne)", fontSize: 32, fontWeight: 800, color: "var(--ns-g)", letterSpacing: "-1px" }}>
          {total.toLocaleString()}
          <span style={{ fontSize: 16, color: "var(--ns-muted)", marginLeft: 6 }}>THB</span>
        </div>
        <div style={{ fontSize: 13, color: "var(--ns-muted)", marginTop: 4 }}>
          {settled}/{tripBills.length} bills settled
        </div>
      </div>
 
      {/* ── Category breakdown ── */}
      <div className="ns-section-label">By Category</div>
      <div className="ns-card" style={{ marginBottom: 14 }}>
        {Object.entries(catMap).sort((a, b) => b[1] - a[1]).map(([cat, amt]) => (
          <div key={cat} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "8px 0", borderBottom: "1px solid var(--ns-border)" }}>
            <span style={{ fontSize: 14, color: "var(--ns-text)" }}>{getCategoryIcon(cat)} {cat}</span>
            <span style={{ fontFamily: "var(--ns-syne)", fontWeight: 700, color: "var(--ns-y)", fontSize: 14 }}>
              {amt.toLocaleString()} THB
            </span>
          </div>
        ))}
      </div>
 
      {/* ── Balances ── */}
      <div className="ns-section-label">Balances</div>
      <div className="ns-card" style={{ marginBottom: 14 }}>
        {Object.entries(balances).map(([name, bal]) => {
          const isPos = bal >= 0;
          return (
            <div key={name} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "8px 0", borderBottom: "1px solid var(--ns-border)" }}>
              <span style={{ fontSize: 14, color: "var(--ns-text)" }}>{name}</span>
              <span style={{ fontFamily: "var(--ns-syne)", fontWeight: 700, fontSize: 14, color: isPos ? "var(--ns-g)" : "var(--ns-r)" }}>
                {isPos ? "+" : ""}{bal.toFixed(2)} THB
              </span>
            </div>
          );
        })}
      </div>
 
      {/* ── All bills ── */}
      <div className="ns-section-label">All Bills</div>
      {tripBills.map((bill, i) => (
        <div key={i} className="ns-card" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
          <div>
            <div style={{ fontSize: 14, fontWeight: 600, color: "var(--ns-text)" }}>{bill.name}</div>
            <div style={{ fontSize: 11, color: "var(--ns-muted)" }}>Paid by {bill.paidBy} · {bill.date}</div>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontFamily: "var(--ns-syne)", fontSize: 14, fontWeight: 800, color: "var(--ns-y)" }}>
              {Number(bill.amount).toLocaleString()}
            </div>
            <span className={`ns-badge ${bill.status === "Finished" ? "ns-badge-green" : "ns-badge-yellow"}`} style={{ fontSize: 10 }}>
              {bill.status === "Finished" ? "✅" : "⏳"}
            </span>
          </div>
        </div>
      ))}
 
      {/* ── Actions ── */}
      <button className="ns-btn ns-btn-primary" style={{ marginTop: 8 }} onClick={handleShare}>
        📤 Share / Copy Summary
      </button>
      <button className="ns-btn ns-btn-ghost" style={{ marginTop: 10 }} onClick={() => setPage("settlement")}>
        ← Back
      </button>
    </div>
  );
}
 
export default ExportSummary;